- name: lihas_variabled
  src: https://github.com/LinuxHaus/ansible_lihas_variables.git
  version: origin/master
- name: lihas_dehydrated
  src: https://github.com/LinuxHaus/ansible_lihas_dehydrated.git
  version: origin/master
