---
- name: Include variables
  ansible.builtin.include_role:
    name: lihas_variables
  when: configspaces is not defined
- name: Install haproxy
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - haproxy
  loop_control:
    loop_var: item

# setup haproxy
- name: Base configuration for haproxy
  ansible.builtin.copy:
    dest: "{{ item }}"
    src: "files/{{ item }}"
    mode: "0644"
  loop:
    - "/etc/haproxy/haproxy.cfg"
  loop_control:
    loop_var: item
  notify: Reload haproxy
